### PR TITLE
usb: Make ADB initialization persistently switchable at boot

### PR DESCRIPTION
**Pull request by PsychoGame**
This patch consists of three merges from my wip-adb branch.
- usb; Initial changes to accomodate combined usb scripts
- usb: Create combined usb-normalboot and usb-noadb
- usb: Stiching adbcheck and usb-normalboot together.

The persisting adb magic in the misc partition must be set with the help of the OpenQTI interface,
During modem boot, the usb initialization script will run at a certain point.
What this will do is obtain the current value of the adb magic from the misc partition
Based on the value it is stored, the usb initialization will either boot with or without ADB.
ADB will be disabled only when the returnvalue of adbcheck is 1.
All other cases will lead to initialization of the ADB Daemon, to accommodate debugging.

### CODE REVIEW

**Comment by PsychoGame** [comment]
Hello @Biktorgj,

Please let me knowwhat you think of it.

**Comment by Biktorgj** [comment]
Hi and first of all thanks for helping me out!
Just built an image based on your changes, but doesn't seem to be working for me, either with ADB enabled or disabled (as checked from adbcheck) ADB is always on.

It looks from the commit you tried to merge both scripts to avoid breaking anything, but there's nothing special in usb-noadb that we need keeping. If you look at recipes-modem/openqti/files/inc/atfwd.h, the only things we need to handle different is the enabled functions in the USB gadget driver: 

``

    {true, "tty,smd,smd", "diag,serial,rmnet,ffs"},       // With ADB

    {false, "tty,smd,smd", "diag,serial,rmnet"},          // Without ADB

    {true, "tty,smd,smd", "diag,serial,rmnet,ffs,audio"}, // USB audio + ADB

    {false, "tty,smd,smd", "diag,serial,rmnet,audio"}, // USB audio without ADB

``

All the rest stays the same, I think we can remove usb-noadb entirely (that was some leftover from the previous release), and just set `/sys/class/android_usb/android0/functions` from the result of adbcheck. What do you think?

**Comment by PsychoGame** [comment]
Hello @Biktorgj,

I'm very happy to try and help you out any way I can.
For me the initialization script was working properly, although without the use of the adbcheck utility you created (So just by setting adb_setting=1).
I wasn't able tot create a building image with yocto, as my travel notebook is quite low on resources (hdd space/CPU/ram wise).
Would you be able to share your image with me?
It's exactly what you describe what I tried to accomplish.
The usb-noadb config worked for me, so indeed I tried to combine it.
What I think happens is that the script doesn't correctly pick-up the return value of the adbcheck.
Maybe you could also try to force set the value to 1, then if it works then, then that confirms my theory.
But if a lot of stuff trom the usb-noadb config is unneccasary I can simplify it a lot more.
I'll do soms more experimentation with the script in the meantime.
Edit 1: Forgot to say, but I like your implementation more indeed.
Much cleaner and has no unnecessary stuff inside.
I'll try to rewrite it some more, but having the binaries of adbcheck and the corresponding openqti would help some more in testing.

**Comment by Biktorgj** [comment]
This is the result on boot:
pine64-pinephone:/home/user# lsusb
Bus 005 Device 001: ID 1d6b:0002
Bus 003 Device 001: ID 1d6b:0001
Bus 002 Device 010: ID 2c7c:0125
Bus 001 Device 001: ID 1d6b:0002
Bus 004 Device 001: ID 1d6b:0001
Bus 002 Device 001: ID 1d6b:0002
pine64-pinephone:/home/user# adb shell
sh-5.1# adbcheck
Persistent ADB is disabled
sh-5.1# 

If you're going to be messing around with init files, here's a pro-tip: Don't flash this rootfs image to the system partition, use the recoveryfs partition and jump to it from fastboot with `fastboot oem reboot-recovery`. That way if USB doesn't start or there's some hard unrecoverable problem you just need to reboot the pinephone and you'll be able to easily reboot into the main modem firmware again :)
Here's a copy of the image with your changes: 

[test_usb.tar.gz](https://github.com/Biktorgj/meta-qcom/files/6837997/test_usb.tar.gz)

**Comment by PsychoGame** [comment]
> This is the result on boot:
> pine64-pinephone:/home/user# lsusb
> Bus 005 Device 001: ID 1d6b:0002
> Bus 003 Device 001: ID 1d6b:0001
> Bus 002 Device 010: ID 2c7c:0125
> Bus 001 Device 001: ID 1d6b:0002
> Bus 004 Device 001: ID 1d6b:0001
> Bus 002 Device 001: ID 1d6b:0002
> pine64-pinephone:/home/user# adb shell
> sh-5.1# adbcheck
> Persistent ADB is disabled
> sh-5.1#
> 
> If you're going to be messing around with init files, here's a pro-tip: Don't flash this rootfs image to the system partition, use the recoveryfs partition and jump to it from fastboot with `fastboot oem reboot-recovery`. That way if USB doesn't start or there's some hard unrecoverable problem you just need to reboot the pinephone and you'll be able to easily reboot into the main modem firmware again :)

Thank you for the tip, didn't know that to be honest. I already found out the hard way that it can be quite tricky.
I had to open up the phone and do it with the jumper wire to get the modem into EDL-mode.
But later on, when I broke it again, I found another trick to be working as well without the need to open up the phone completely.
What I did was the  following, so maybe it can help others  as well:
- Shutdown the phone.
- Put the modem related kill-switches to the killed state (I only disabled the first and 2nd one)
- Reboot the phone.
- In terminal issue a fastboot oem stay
- Re-enable the modem by switching the kill switches to the "on" state again.
- And last step was to restart the  eg25-manager with "systemctl restart eg25-manager"
- This tried to initialize the modem again, but made it stay in fastboot state so I could flash everything back again.

> Here's a copy of the image with your changes:
> 
> [test_usb.tar.gz](https://github.com/Biktorgj/meta-qcom/files/6837997/test_usb.tar.gz)
Thank you, I'm downloading it right now, and will do some testing and alterations to the usb-initialization script.
First I will try to figure out why the reading of the adbcheck in the script is not working as I hoped it would.

**Comment by PsychoGame** [comment]
Hello @Biktorgj,

I must have been sleeping when I uploaded the code to my github.
A big mistake was made, probably by pasting the written script into the usb script.
With the addition of the latest two commits this script is working properly.
Now I will clean out the unnecessary stuff later, but at least you can test it out to see it operational.

**Comment by Biktorgj** [comment]
Okay this works better :) 
For some reason (don't have persistent logging enabled so I couldn't see) ADB doesn't start right away when switching from disabled->enabled needing a reboot, something will probably be failing in either the script or openqti when doing a restart, but that's something we'll take care of later.

Edit to add: I loved your trick to force cold start the modem, and if you don't mind, I'm going to add it to the documentation :)

[test2_usb.tar.gz](https://github.com/Biktorgj/meta-qcom/files/6852849/test2_usb.tar.gz)

**Comment by PsychoGame** [comment]
Hello @Biktorgj,

Of course you can add that to the documentation.
The more knowledge shared the better.
It's much simpler than to fully have to take the phone apart.
Hopefully this might lower the bar for others to join in development as well. 
It looks like it has something to do with the script, but I'm looking into it already.
Also I noticed that in kernel we use the Android Gadget driver for USB initialization.
Maybe we can try to switch over to the mainline kernel ConfigFS gadget driver?
This might prove to be better for futures mainline kernel like the one Konrad is working on.
Mainline doesn't have the Android Gadget support.

**Comment by Biktorgj** [comment]
Hi again, the reason to use the Android USB gadget is for compatibility with the userspace. ModemManager for example expects to be able to speak through QMI with the modem (that's how it sets up APNs, gets notified of phone calls etc.), and ConfigFS doesn't have support for that. If we were to use the configfs driver we would need to port a lot stuff from the Android Gadget and add a lot of driver support in oFono/ModemManager to make everything work. I don't know if newer kernels bundle support for mbim/qrtr/qmi/diag over configfs, if they do, we'll probably be able to make that work :)

**Comment by PsychoGame** [comment]
Thank you for your clarification as to why we use the android_usb gadget driver.
Shall I look into the mainline gadget driver and see how far I can get with it?
I will make a separate PR for this, so it doesn't clutter this topic.
At least this latest change to this PR is the most minimalistic approach for switching ADB setting at boot.
Only thing remaining is the "online" re-initialization of adb function.

Edit 1: I see you switched off the sleep timer completely.
While 10 seconds of sleep timer is quite high in my opinion, disabling completely might give problems in the userspace.
This sometimes needs some time to set things up properly.
I've seen a lot of implementations use sleep timers of 4 instead of 10.
On my modem i've replaced the following:
        echo "Quectel, Incorporated" > /sys/class/android_usb/android0/iManufacturer
        echo "LTE Module" > /sys/class/android_usb/android0/iProduct
        echo 1 > /sys/class/android_usb/android0/enable
With:
        echo "Quectel, Incorporated" > /sys/class/android_usb/android0/iManufacturer
        echo "LTE Module" > /sys/class/android_usb/android0/iProduct
        echo 1 > /sys/class/android_usb/android0/enable
        sleep 4

**Comment by Biktorgj** [comment]
We really shouldnt need a hard sleep timer, usb can be ready at the 7 second mark but modemmanager complains about audio capabilities if it starts too soon. I'm currently trying to figure out why is that so we can have a PIN ready modem in 15 seconds but not quite there yet :)

**Pull request merged**
