### PR TITLE
Fixed USBAUD mode. Improved usbmode handling. Added USBAUD persistance

### PR DESCRIPTION
**Pull request by gregvish**
Added the correct AFE mixer selection when in USBAUD mode.
Changed the `current_usb_mode` handling to help with choosing the correct mixer according to the usbmode.
Added persistence to the USBAUD mode.

Edit: I've tested this reasonably. What I couldn't test is VoLTE, and the I2S working after changing the mode back.

### CODE REVIEW

**Comment by Biktorgj** [comment]
Hi!
Sorry for the delay but didn't have time yesterday to give it a look

This isn't building for me, it conplains about current_usb_mode being declared twice. I see it's both in code and header file, is it compiling for you?

**Comment by gregvish** [comment]
I'm compiling this simply using `arm-linux-gnueabi-gcc -static -o openqti *.c -I../inc -lpthread`, as I a didn't want to set up the full environment. Strangely it compiles just fine this way... I changed the declaration to `extern`, but if you see another thing like that I'll set up the full environment and make sure it works fine with it.

**Comment by Biktorgj** [comment]
Interesting, first call when switching between LTE -> 3G fails over I2S, can you check if it does the same over USB?

**Comment by Biktorgj** [comment]
Here is a test build of your changes. I think we could use some refactoring here to keep all the running configuration at the same place, but we can do that later. Give it a test run, the only issue I found is first call after switch networks is completely silent, but then changed again and didn't fail so I don't know what to think of it


[usbaudio_test.tar.gz](https://github.com/Biktorgj/meta-qcom/files/6912951/usbaudio_test.tar.gz)

**Comment by gregvish** [comment]
Hi,
Sorry, I didn't have the time to debug this for a few days. I did a small fix, but it can't be the issue you're describing. I'll try to figure it out.
I do notice that in calls where the modem is switching from LTE to UMTS for CS-voice, it takes a fairly long time for the switch to occur, and a few first seconds of the call are silent. I assume that's not what you mean here.

**Be careful with publicly posting those logs**
The audio path switching takes a few seconds here.

**Comment by Biktorgj** [comment]
That should be normal, as the modem needs to renegotiate with the BTS from LTE -> whatever is going to so it can loose a couple of seconds doing it before reattempting the call. What I've noticed is that after the network change first call is completely silent (going to add timestamps to that log, ot's fairly difficult to track anything postmortem this way)

The call and usb handling is a piece of shit as it is so I'm rebuilding it anyway (have it half done), but please let me know if the provided image works for you.

If it does, I'll merge this in and rebase my changes so hopefully 0.3.0 can have built in usb audio support... With the bugs removed!

I'm moving all the usb status reading to openqti.c, and signal from there to the rest. The small adbcheck utility will output both adb and usb audio settings so the init script can apply the functions correctly, and I'm reworking handle_audio_pkt so it has more sense... There's no reason for atfwd daemon to have all the usb manipulation when it should only be triggering functions from somewhere else... Hopefully it will make sense when it's all in order :)

**Comment by gregvish** [comment]
At first, flashing this image didn't work for me, openqti was stuck in a loop of:
`[WRN]init_port_mapper: Waiting for the Dynamic port mapper to become ready... `
I re-flashed a few images back and forth (to stock), and eventually this one worked too. I really don't know what that was about.
Except for this incident, it does work reliably for me now.
>needs to renegotiate with the BTS from LTE -> whatever is going to so it can loose a couple of seconds doing it before reattempting the call.

That's not exactly what I mean. After the switch, when the call is already established, the mixer configuration takes too long to set up. The result is that the other side of the call is already talking before I can hear them. For the few first seconds of the call. I guess this is only a problem when calling numbers that answer immediately (automated response). Not really important.

**Pull request closed without merging**
